---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    #namesapce omitted since ClusterRoles are not namespaced
    name: secret-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRoleBinding'
metadata:
    name: 'terraform-namespaces'
roleRef:
    apiGroup: 'rbac.authorization.k8s.io'
    kind: 'ClusterRole'
    name: 'secret-reader'
subjects:
    - kind: ServiceAccount
      name: default
      namespace: jenkins-slave
