- name: Cleanup the Resources
  hosts: localhost
  tasks:
  - name: iot platform Cleanup
    include_role:
      name: iot
      tasks_from: cleanup
  environment:
    ARM_SUBSCRIPTION_ID: "{{ ARM_SUBSCRIPTION_ID | default('') }}"
    ARM_TENANT_ID: "{{ ARM_TENANT_ID | default('') }}"
    ARM_CLIENT_ID: "{{ ARM_CLIENT_ID | default('') }}"
    ARM_CLIENT_SECRET: "{{ ARM_CLIENT_SECRET | default('') }}"

